- name: 配置 wrangler.toml
  run: |
    cat > wrangler.toml << EOF
    name = "${{ secrets.CF_WORKER_NAME }}"
    main = "worker.js"
    compatibility_date = "2024-01-01"
    account_id = "${{ secrets.CF_ACCOUNT_ID }}"

    [[d1_databases]]
    binding = "DB"
    database_name = "emby-proxy-db"
    database_id = "5e646df8-b638-4352-bf6b-e8f1317e213f"
    EOF
